# Generated by Django 4.2.7 on 2023-11-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='total_slot',
        ),
    ]
