# Generated by Django 4.2.7 on 2023-11-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_keywords_event_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': 'Keywords', 'verbose_name_plural': 'Keywords'},
        ),
    ]
